# Generated by Django 3.0.10 on 2020-10-09 16:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('male', '男'), ('female', '女'), ('other', '無')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='preferred_office',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('changhua', '彰化市'), ('yuanlin', '員林市')], max_length=16, null=True),
        ),
    ]
