# Generated by Django 3.0.10 on 2020-10-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0002_auto_20201009_1642'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pet_name', models.CharField(max_length=100, null=True)),
                ('pet_name_english', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.CharField(max_length=30)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
                ('alive', models.BooleanField(default=True)),
                ('death_day', models.DateField(blank=True, null=True)),
                ('sex', multiselectfield.db.fields.MultiSelectField(choices=[('male', '男'), ('female', '女')], max_length=11)),
                ('neutered', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('blood_type', models.CharField(max_length=2, null=True)),
                ('colour', models.CharField(max_length=100)),
                ('temper', models.CharField(blank=True, max_length=500, null=True)),
                ('allergies', models.CharField(blank=True, max_length=500, null=True)),
                ('preconditions', models.CharField(blank=True, max_length=500, null=True)),
                ('other_pets', models.CharField(blank=True, max_length=100, null=True)),
                ('other_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_visit', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pet_picture', models.FileField(upload_to='documents')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pets',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Owner.Owner')),
                ('pet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pet.Pet')),
            ],
            options={
                'verbose_name_plural': 'pet_owners',
                'db_table': 'pet_owner',
            },
        ),
    ]
