# Generated by Django 3.0.10 on 2020-10-09 18:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_name_english',
        ),
        migrations.AlterField(
            model_name='pet',
            name='blood_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='neutered',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('yes', 'yes'), ('no', 'no'), ('unknown', 'unknown')], max_length=14),
        ),
    ]
